steps:

  - id: Unit Tests
    name: python:3.9-buster
    entrypoint: bash
    args:
    - '-c'
    - |
        # Substitute tag name / version
        sed -i 's/%VERSION%/'$TAG_NAME'/g' setup.cfg

        # Install dependencies
        pip install -r requirements.txt --user

        # Execute build workflow
        python -m tox

        # Capture test results
        cp coverage/junit.xml alexei_lib_${TAG_NAME}_${SHORT_SHA}_test_log.xml

        # Build release
        python -m build

  - id: Publish
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: bash
    args:
    - '-c'
    - |
        echo "Establishing test results..."
        echo alexei_lib_${TAG_NAME}_${SHORT_SHA}_test_log.xml

        echo "Publishing test results..."
        gsutil cp alexei_lib_${TAG_NAME}_${SHORT_SHA}_test_log.xml gs://${_LOG_BUCKET}

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:

  _LOG_BUCKET:  alx-fis3g-release-logs
