steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Substitute the version
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args: ["-c", "sed -i 's/%VERSION%/'$TAG_NAME'/g' setup.cfg"]

  # Run unit tests
  - name: python
    entrypoint: python
    args: ["-m", "tox"]

  # Capture results
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args: ["-c", "cp coverage/junit.xml ${SHORT_SHA}_test_log.xml"]

# Save test logs to Google Cloud Storage
artifacts:
  objects:
    location: gs://${_BUCKET_NAME}/
    paths:
      - ${SHORT_SHA}_test_log.xml

substitutions:
  _BUCKET_NAME: logs-hmjbvyp8eqyefrh

# Store images in Google Artifact Registry 
# images:
#   - us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/myimage:${SHORT_SHA}
